[package]
name = "time-interface"
version = "0.1.0"
description = "Interface library for the time-interface time capability, "
authors = [ "dev@example.com" ]
edition = "2018"
license = "Apache-2.0"

# when publishing to crates.io, freeze src by omitting build.rs
exclude = [ "build.rs" ]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
async-trait = "0.1"
futures = "0.3"
serde = { version = "1.0" , features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11"
#wasmbus-rpc = { git = "https://github.com/based-template/weld.git" }
wasmbus-rpc = "0.5.2"

[dev-dependencies]
base64 = "0.13"

# build-dependencies needed for build.rs
[build-dependencies]
weld-codegen = "0.2.3"
